# Feature Groups' feature names
TES_COM = [
    "TES_CountDeclFunction",
    "TES_CountLine",
    "TES_CountLineBlank",
    "TES_CountLineCode",
    "TES_CountLineCodeDecl",
    "TES_CountLineCodeExe",
    "TES_CountLineComment",
    "TES_CountStmt",
    "TES_CountStmtDecl",
    "TES_CountStmtExe",
    "TES_RatioCommentToCode",
    "TES_MaxCyclomatic",
    "TES_MaxCyclomaticModified",
    "TES_MaxCyclomaticStrict",
    "TES_MaxEssential",
    "TES_MaxNesting",
    "TES_SumCyclomatic",
    "TES_SumCyclomaticModified",
    "TES_SumCyclomaticStrict",
    "TES_SumEssential",
    "TES_CountDeclClass",
    "TES_CountDeclClassMethod",
    "TES_CountDeclClassVariable",
    "TES_CountDeclExecutableUnit",
    "TES_CountDeclInstanceMethod",
    "TES_CountDeclInstanceVariable",
    "TES_CountDeclMethod",
    "TES_CountDeclMethodDefault",
    "TES_CountDeclMethodPrivate",
    "TES_CountDeclMethodProtected",
    "TES_CountDeclMethodPublic",
]

TES_PRO = [
    "TES_CommitCount",
    "TES_DistinctDevCount",
    "TES_OwnersContribution",
    "TES_MinorContributorCount",
    "TES_OwnersExperience",
    "TES_AllCommitersExperience",
]

TES_CHN = [
    "TES_LinesAdded",
    "TES_LinesDeleted",
    "TES_AddedChangeScattering",
    "TES_DeletedChangeScattering",
    "TES_DMMSize",
    "TES_DMMComplexity",
    "TES_DMMInterfacing",
]

REC = [
    "REC_AvgExeTime",
    "REC_MaxExeTime",
    "REC_Age",
    "REC_FailRate",
    "REC_AssertRate",
    "REC_ExcRate",
    "REC_LastVerdict",
    "REC_LastExeTime",
]

COV = ["COV_ChnScoreSum", "COV_ImpScoreSum", "COV_ChnCount", "COV_ImpCount"]

COD_COV_COM = [
    "COD_COV_CHN_CountDeclFunction",
    "COD_COV_CHN_CountLine",
    "COD_COV_CHN_CountLineBlank",
    "COD_COV_CHN_CountLineCode",
    "COD_COV_CHN_CountLineCodeDecl",
    "COD_COV_CHN_CountLineCodeExe",
    "COD_COV_CHN_CountLineComment",
    "COD_COV_CHN_CountStmt",
    "COD_COV_CHN_CountStmtDecl",
    "COD_COV_CHN_CountStmtExe",
    "COD_COV_CHN_RatioCommentToCode",
    "COD_COV_CHN_MaxCyclomatic",
    "COD_COV_CHN_MaxCyclomaticModified",
    "COD_COV_CHN_MaxCyclomaticStrict",
    "COD_COV_CHN_MaxEssential",
    "COD_COV_CHN_MaxNesting",
    "COD_COV_CHN_SumCyclomatic",
    "COD_COV_CHN_SumCyclomaticModified",
    "COD_COV_CHN_SumCyclomaticStrict",
    "COD_COV_CHN_SumEssential",
    "COD_COV_CHN_CountDeclClass",
    "COD_COV_CHN_CountDeclClassMethod",
    "COD_COV_CHN_CountDeclClassVariable",
    "COD_COV_CHN_CountDeclExecutableUnit",
    "COD_COV_CHN_CountDeclInstanceMethod",
    "COD_COV_CHN_CountDeclInstanceVariable",
    "COD_COV_CHN_CountDeclMethod",
    "COD_COV_CHN_CountDeclMethodDefault",
    "COD_COV_CHN_CountDeclMethodPrivate",
    "COD_COV_CHN_CountDeclMethodProtected",
    "COD_COV_CHN_CountDeclMethodPublic",
    "COD_COV_IMP_CountDeclFunction",
    "COD_COV_IMP_CountLine",
    "COD_COV_IMP_CountLineBlank",
    "COD_COV_IMP_CountLineCode",
    "COD_COV_IMP_CountLineCodeDecl",
    "COD_COV_IMP_CountLineCodeExe",
    "COD_COV_IMP_CountLineComment",
    "COD_COV_IMP_CountStmt",
    "COD_COV_IMP_CountStmtDecl",
    "COD_COV_IMP_CountStmtExe",
    "COD_COV_IMP_RatioCommentToCode",
    "COD_COV_IMP_MaxCyclomatic",
    "COD_COV_IMP_MaxCyclomaticModified",
    "COD_COV_IMP_MaxCyclomaticStrict",
    "COD_COV_IMP_MaxEssential",
    "COD_COV_IMP_MaxNesting",
    "COD_COV_IMP_SumCyclomatic",
    "COD_COV_IMP_SumCyclomaticModified",
    "COD_COV_IMP_SumCyclomaticStrict",
    "COD_COV_IMP_SumEssential",
    "COD_COV_IMP_CountDeclClass",
    "COD_COV_IMP_CountDeclClassMethod",
    "COD_COV_IMP_CountDeclClassVariable",
    "COD_COV_IMP_CountDeclExecutableUnit",
    "COD_COV_IMP_CountDeclInstanceMethod",
    "COD_COV_IMP_CountDeclInstanceVariable",
    "COD_COV_IMP_CountDeclMethod",
    "COD_COV_IMP_CountDeclMethodDefault",
    "COD_COV_IMP_CountDeclMethodPrivate",
    "COD_COV_IMP_CountDeclMethodProtected",
    "COD_COV_IMP_CountDeclMethodPublic",
]

COD_COV_PRO = [
    "COD_COV_CHN_CommitCount",
    "COD_COV_CHN_DistinctDevCount",
    "COD_COV_CHN_OwnersContribution",
    "COD_COV_CHN_MinorContributorCount",
    "COD_COV_CHN_OwnersExperience",
    "COD_COV_CHN_AllCommitersExperience",
    "COD_COV_IMP_CommitCount",
    "COD_COV_IMP_DistinctDevCount",
    "COD_COV_IMP_OwnersContribution",
    "COD_COV_IMP_MinorContributorCount",
    "COD_COV_IMP_OwnersExperience",
    "COD_COV_IMP_AllCommitersExperience",
]

COD_COV_CHN = [
    "COD_COV_CHN_LinesAdded",
    "COD_COV_CHN_LinesDeleted",
    "COD_COV_CHN_AddedChangeScattering",
    "COD_COV_CHN_DeletedChangeScattering",
    "COD_COV_CHN_DMMSize",
    "COD_COV_CHN_DMMComplexity",
    "COD_COV_CHN_DMMInterfacing",
]

DET_COV = ["DET_COV_CHN_Faults", "DET_COV_IMP_Faults"]

# Features' names which are related to impacted files
IMPACTED_FEATURES = [
    "COV_ImpScoreSum",
    "COV_ImpCount",
    "COD_COV_IMP_CountDeclFunction",
    "COD_COV_IMP_CountLine",
    "COD_COV_IMP_CountLineBlank",
    "COD_COV_IMP_CountLineCode",
    "COD_COV_IMP_CountLineCodeDecl",
    "COD_COV_IMP_CountLineCodeExe",
    "COD_COV_IMP_CountLineComment",
    "COD_COV_IMP_CountStmt",
    "COD_COV_IMP_CountStmtDecl",
    "COD_COV_IMP_CountStmtExe",
    "COD_COV_IMP_RatioCommentToCode",
    "COD_COV_IMP_MaxCyclomatic",
    "COD_COV_IMP_MaxCyclomaticModified",
    "COD_COV_IMP_MaxCyclomaticStrict",
    "COD_COV_IMP_MaxEssential",
    "COD_COV_IMP_MaxNesting",
    "COD_COV_IMP_SumCyclomatic",
    "COD_COV_IMP_SumCyclomaticModified",
    "COD_COV_IMP_SumCyclomaticStrict",
    "COD_COV_IMP_SumEssential",
    "COD_COV_IMP_CountDeclClass",
    "COD_COV_IMP_CountDeclClassMethod",
    "COD_COV_IMP_CountDeclClassVariable",
    "COD_COV_IMP_CountDeclExecutableUnit",
    "COD_COV_IMP_CountDeclInstanceMethod",
    "COD_COV_IMP_CountDeclInstanceVariable",
    "COD_COV_IMP_CountDeclMethod",
    "COD_COV_IMP_CountDeclMethodDefault",
    "COD_COV_IMP_CountDeclMethodPrivate",
    "COD_COV_IMP_CountDeclMethodProtected",
    "COD_COV_IMP_CountDeclMethodPublic",
    "COD_COV_IMP_CommitCount",
    "COD_COV_IMP_DistinctDevCount",
    "COD_COV_IMP_OwnersContribution",
    "COD_COV_IMP_MinorContributorCount",
    "COD_COV_IMP_OwnersExperience",
    "COD_COV_IMP_AllCommitersExperience",
    "DET_COV_IMP_Faults",
]
