# Feature Groups' feature names
TES_COM = [
    "TES_COM_CountDeclFunction",
    "TES_COM_CountLine",
    "TES_COM_CountLineBlank",
    "TES_COM_CountLineCode",
    "TES_COM_CountLineCodeDecl",
    "TES_COM_CountLineCodeExe",
    "TES_COM_CountLineComment",
    "TES_COM_CountStmt",
    "TES_COM_CountStmtDecl",
    "TES_COM_CountStmtExe",
    "TES_COM_RatioCommentToCode",
    "TES_COM_MaxCyclomatic",
    "TES_COM_MaxCyclomaticModified",
    "TES_COM_MaxCyclomaticStrict",
    "TES_COM_MaxEssential",
    "TES_COM_MaxNesting",
    "TES_COM_SumCyclomatic",
    "TES_COM_SumCyclomaticModified",
    "TES_COM_SumCyclomaticStrict",
    "TES_COM_SumEssential",
    "TES_COM_CountDeclClass",
    "TES_COM_CountDeclClassMethod",
    "TES_COM_CountDeclClassVariable",
    "TES_COM_CountDeclExecutableUnit",
    "TES_COM_CountDeclInstanceMethod",
    "TES_COM_CountDeclInstanceVariable",
    "TES_COM_CountDeclMethod",
    "TES_COM_CountDeclMethodDefault",
    "TES_COM_CountDeclMethodPrivate",
    "TES_COM_CountDeclMethodProtected",
    "TES_COM_CountDeclMethodPublic",
]

TES_PRO = [
    "TES_PRO_CommitCount",
    "TES_PRO_DistinctDevCount",
    "TES_PRO_OwnersContribution",
    "TES_PRO_MinorContributorCount",
    "TES_PRO_OwnersExperience",
    "TES_PRO_AllCommitersExperience",
]

TES_CHN = [
    "TES_CHN_LinesAdded",
    "TES_CHN_LinesDeleted",
    "TES_CHN_AddedChangeScattering",
    "TES_CHN_DeletedChangeScattering",
    "TES_CHN_DMMSize",
    "TES_CHN_DMMComplexity",
    "TES_CHN_DMMInterfacing",
]

REC = [
    "REC_AvgExeTime",
    "REC_MaxExeTime",
    "REC_Age",
    "REC_FailRate",
    "REC_AssertRate",
    "REC_ExcRate",
    "REC_LastVerdict",
    "REC_LastExeTime",
]

COV = ["COV_ChnScoreSum", "COV_ImpScoreSum", "COV_ChnCount", "COV_ImpCount"]

COD_COV_COM = [
    "COD_COV_COM_C_CountDeclFunction",
    "COD_COV_COM_C_CountLine",
    "COD_COV_COM_C_CountLineBlank",
    "COD_COV_COM_C_CountLineCode",
    "COD_COV_COM_C_CountLineCodeDecl",
    "COD_COV_COM_C_CountLineCodeExe",
    "COD_COV_COM_C_CountLineComment",
    "COD_COV_COM_C_CountStmt",
    "COD_COV_COM_C_CountStmtDecl",
    "COD_COV_COM_C_CountStmtExe",
    "COD_COV_COM_C_RatioCommentToCode",
    "COD_COV_COM_C_MaxCyclomatic",
    "COD_COV_COM_C_MaxCyclomaticModified",
    "COD_COV_COM_C_MaxCyclomaticStrict",
    "COD_COV_COM_C_MaxEssential",
    "COD_COV_COM_C_MaxNesting",
    "COD_COV_COM_C_SumCyclomatic",
    "COD_COV_COM_C_SumCyclomaticModified",
    "COD_COV_COM_C_SumCyclomaticStrict",
    "COD_COV_COM_C_SumEssential",
    "COD_COV_COM_C_CountDeclClass",
    "COD_COV_COM_C_CountDeclClassMethod",
    "COD_COV_COM_C_CountDeclClassVariable",
    "COD_COV_COM_C_CountDeclExecutableUnit",
    "COD_COV_COM_C_CountDeclInstanceMethod",
    "COD_COV_COM_C_CountDeclInstanceVariable",
    "COD_COV_COM_C_CountDeclMethod",
    "COD_COV_COM_C_CountDeclMethodDefault",
    "COD_COV_COM_C_CountDeclMethodPrivate",
    "COD_COV_COM_C_CountDeclMethodProtected",
    "COD_COV_COM_C_CountDeclMethodPublic",
    "COD_COV_COM_IMP_CountDeclFunction",
    "COD_COV_COM_IMP_CountLine",
    "COD_COV_COM_IMP_CountLineBlank",
    "COD_COV_COM_IMP_CountLineCode",
    "COD_COV_COM_IMP_CountLineCodeDecl",
    "COD_COV_COM_IMP_CountLineCodeExe",
    "COD_COV_COM_IMP_CountLineComment",
    "COD_COV_COM_IMP_CountStmt",
    "COD_COV_COM_IMP_CountStmtDecl",
    "COD_COV_COM_IMP_CountStmtExe",
    "COD_COV_COM_IMP_RatioCommentToCode",
    "COD_COV_COM_IMP_MaxCyclomatic",
    "COD_COV_COM_IMP_MaxCyclomaticModified",
    "COD_COV_COM_IMP_MaxCyclomaticStrict",
    "COD_COV_COM_IMP_MaxEssential",
    "COD_COV_COM_IMP_MaxNesting",
    "COD_COV_COM_IMP_SumCyclomatic",
    "COD_COV_COM_IMP_SumCyclomaticModified",
    "COD_COV_COM_IMP_SumCyclomaticStrict",
    "COD_COV_COM_IMP_SumEssential",
    "COD_COV_COM_IMP_CountDeclClass",
    "COD_COV_COM_IMP_CountDeclClassMethod",
    "COD_COV_COM_IMP_CountDeclClassVariable",
    "COD_COV_COM_IMP_CountDeclExecutableUnit",
    "COD_COV_COM_IMP_CountDeclInstanceMethod",
    "COD_COV_COM_IMP_CountDeclInstanceVariable",
    "COD_COV_COM_IMP_CountDeclMethod",
    "COD_COV_COM_IMP_CountDeclMethodDefault",
    "COD_COV_COM_IMP_CountDeclMethodPrivate",
    "COD_COV_COM_IMP_CountDeclMethodProtected",
    "COD_COV_COM_IMP_CountDeclMethodPublic",
]

COD_COV_PRO = [
    "COD_COV_PRO_C_CommitCount",
    "COD_COV_PRO_C_DistinctDevCount",
    "COD_COV_PRO_C_OwnersContribution",
    "COD_COV_PRO_C_MinorContributorCount",
    "COD_COV_PRO_C_OwnersExperience",
    "COD_COV_PRO_C_AllCommitersExperience",
    "COD_COV_PRO_IMP_CommitCount",
    "COD_COV_PRO_IMP_DistinctDevCount",
    "COD_COV_PRO_IMP_OwnersContribution",
    "COD_COV_PRO_IMP_MinorContributorCount",
    "COD_COV_PRO_IMP_OwnersExperience",
    "COD_COV_PRO_IMP_AllCommitersExperience",
]

COD_COV_CHN = [
    "COD_COV_CHN_C_LinesAdded",
    "COD_COV_CHN_C_LinesDeleted",
    "COD_COV_CHN_C_AddedChangeScattering",
    "COD_COV_CHN_C_DeletedChangeScattering",
    "COD_COV_CHN_C_DMMSize",
    "COD_COV_CHN_C_DMMComplexity",
    "COD_COV_CHN_C_DMMInterfacing",
]

DET_COV = ["DET_COV_C_Faults", "DET_COV_IMP_Faults"]

# Features' names which are related to impacted files
IMPACTED_FEATURES = [
    "COV_ImpScoreSum",
    "COV_ImpCount",
    "COD_COV_COM_IMP_CountDeclFunction",
    "COD_COV_COM_IMP_CountLine",
    "COD_COV_COM_IMP_CountLineBlank",
    "COD_COV_COM_IMP_CountLineCode",
    "COD_COV_COM_IMP_CountLineCodeDecl",
    "COD_COV_COM_IMP_CountLineCodeExe",
    "COD_COV_COM_IMP_CountLineComment",
    "COD_COV_COM_IMP_CountStmt",
    "COD_COV_COM_IMP_CountStmtDecl",
    "COD_COV_COM_IMP_CountStmtExe",
    "COD_COV_COM_IMP_RatioCommentToCode",
    "COD_COV_COM_IMP_MaxCyclomatic",
    "COD_COV_COM_IMP_MaxCyclomaticModified",
    "COD_COV_COM_IMP_MaxCyclomaticStrict",
    "COD_COV_COM_IMP_MaxEssential",
    "COD_COV_COM_IMP_MaxNesting",
    "COD_COV_COM_IMP_SumCyclomatic",
    "COD_COV_COM_IMP_SumCyclomaticModified",
    "COD_COV_COM_IMP_SumCyclomaticStrict",
    "COD_COV_COM_IMP_SumEssential",
    "COD_COV_COM_IMP_CountDeclClass",
    "COD_COV_COM_IMP_CountDeclClassMethod",
    "COD_COV_COM_IMP_CountDeclClassVariable",
    "COD_COV_COM_IMP_CountDeclExecutableUnit",
    "COD_COV_COM_IMP_CountDeclInstanceMethod",
    "COD_COV_COM_IMP_CountDeclInstanceVariable",
    "COD_COV_COM_IMP_CountDeclMethod",
    "COD_COV_COM_IMP_CountDeclMethodDefault",
    "COD_COV_COM_IMP_CountDeclMethodPrivate",
    "COD_COV_COM_IMP_CountDeclMethodProtected",
    "COD_COV_COM_IMP_CountDeclMethodPublic",
    "COD_COV_PRO_IMP_CommitCount",
    "COD_COV_PRO_IMP_DistinctDevCount",
    "COD_COV_PRO_IMP_OwnersContribution",
    "COD_COV_PRO_IMP_MinorContributorCount",
    "COD_COV_PRO_IMP_OwnersExperience",
    "COD_COV_PRO_IMP_AllCommitersExperience",
    "DET_COV_IMP_Faults",
]
